apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: bpfman-agent-metrics
  namespace: bpfman
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/name: bpfman-agent-metrics
spec:
  podMetricsEndpoints:
  - port: https-metrics
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
    scrapeTimeout: 30s
  selector:
    matchLabels:
      name: bpfman-daemon
  namespaceSelector:
    matchNames:
    - bpfman