apiVersion: v1
kind: Service
metadata:
  name: bpfman-agent-metrics-headless
  namespace: bpfman
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: agent-metrics-tls
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/name: bpfman-agent-metrics-service
spec:
  clusterIP: None
  ports:
  - name: https-metrics
    port: 8443
    protocol: TCP
    targetPort: https-metrics
  selector:
    name: bpfman-daemon
  publishNotReadyAddresses: true