[package]
name = "creat"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
rusqlite = { version = "0.33.0", features = ["bundled"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
