[package]
name = "bsd" # bsd =~ bpfman sled dumper (Sorry! Naming is hard.)
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
serde = "1.0.217"
serde_json = "1.0.138"
sled = "0.34"
