# Taken from bpfman/bpfman/rustfmt.toml
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
reorder_imports = true
unstable_features = true

# Seem to be common defaults amongst Rust projects.
format_code_in_doc_comments = true
match_block_trailing_comma = true
max_width = 100
newline_style = "Unix"
use_field_init_shorthand = true
use_small_heuristics = "Default"
wrap_comments = true
