#!/usr/bin/env bash

set -euo pipefail

# Override failing test-fmt checks.
autoprat "$@" --throttle 15m --failing-check=ci/prow/test-fmt -c '/override ci/prow/test-fmt' -P
autoprat "$@" --throttle 15m --failing-check=ci/prow/test-fmt -c '/override ci/prow/test-fmt' -P | sh
